Repository EdisonLeeeee/GreatX, pull requests merged in 2022-11, with the labels that each got.

#5 Add ratio for `attacker.data()`, `attacker.edge_flips()`, and `attacker.feat_flips()`
  greatx/attack/flip_attacker.py
  greatx/attack/targeted/pgd_attack.py
  greatx/attack/untargeted/pgd_attack.py
  greatx/nn/models/surrogate.py
Labels: enhancement

#6 Seperate `add_self_loops` and `normalize` arguments in `nn.layers.*`
  greatx/nn/layers/adaptive_conv.py
  greatx/nn/layers/dagnn_conv.py
  greatx/nn/layers/dg_conv.py
  greatx/nn/layers/elastic_conv.py
  greatx/nn/layers/gcn_conv.py
  greatx/nn/layers/robust_conv.py
  greatx/nn/layers/sat_conv.py
  greatx/nn/layers/sg_conv.py
  greatx/nn/layers/soft_median_conv.py
  greatx/nn/layers/ssg_conv.py
  greatx/nn/layers/tag_conv.py
  greatx/nn/models/supervised/jknet.py
  greatx/utils/__init__.py
  greatx/utils/check.py
Labels: refactor

#7 Fix a venue of FeaturePropagation
  README.md
  greatx/defense/feature_propagation.py
Labels: bug, documentation
